#pragma once
#include "Common.h"
#include "System/Object.h"
#include "System/EventArgs.h"
#include "System/Action.h"
#include "System/Collections/Generic/List.h"
#include <type_traits>
#include <utility>

namespace DotNetDupe {
    namespace System {

        /// \class EventHandler
        /// \brief Represents the method that will handle an event when the event provides data.
        ///
        /// \tparam TEventArgs The type of the event data generated by the event. Defaults to EventArgs.
        /// \note Conforms to ECMA-335 Partition IV Section 5.22 (System.EventHandler<TEventArgs>).
        ///       Implements the idiomatic C# publisher-subscriber model with multicast chaining (`+=`, `Add`),
        ///       member method binding (`Add(pInstance, &Class::Method)`), token-based unsubscription (`-=`, `Remove`),
        ///       and sequential invocation (`Invoke`, `operator()`).
        template <typename TEventArgs = EventArgs>
        class EventHandler {
        private:
            struct SubscriberEntry {
                size_t m_nToken;
                Action<const void*, const TEventArgs&> m_fnAction;

                SubscriberEntry() : m_nToken(0), m_fnAction() {}
                SubscriberEntry(size_t nToken, const Action<const void*, const TEventArgs&>& fnAction)
                    : m_nToken(nToken), m_fnAction(fnAction) {}

                bool operator==(const SubscriberEntry& other) const {
                    return m_nToken == other.m_nToken;
                }
            };

            Collections::Generic::List<SubscriberEntry> m_lstSubscribers;
            size_t m_nNextToken;

        public:
            /// \brief Initializes a new empty multicast EventHandler instance.
            EventHandler() : m_lstSubscribers(), m_nNextToken(1) {}

            /// \brief Copy constructor. Copies all subscriber callbacks.
            EventHandler(const EventHandler& other)
                : m_lstSubscribers(other.m_lstSubscribers), m_nNextToken(other.m_nNextToken) {}

            /// \brief Move constructor. Transfers subscriber callbacks.
            EventHandler(EventHandler&& other) noexcept
                : m_lstSubscribers(std::move(other.m_lstSubscribers)), m_nNextToken(other.m_nNextToken) {
                other.m_nNextToken = 1;
            }

            /// \brief Copy assignment operator.
            EventHandler& operator=(const EventHandler& other) {
                if (this != &other) {
                    m_lstSubscribers = other.m_lstSubscribers;
                    m_nNextToken = other.m_nNextToken;
                }
                return *this;
            }

            /// \brief Move assignment operator.
            EventHandler& operator=(EventHandler&& other) noexcept {
                if (this != &other) {
                    m_lstSubscribers = std::move(other.m_lstSubscribers);
                    m_nNextToken = other.m_nNextToken;
                    other.m_nNextToken = 1;
                }
                return *this;
            }

            /// \brief Destructor.
            ~EventHandler() = default;

            /// \brief Subscribes an Action delegate handler and returns a monotonic subscription token.
            /// \param fnHandler The delegate to invoke on event dispatch.
            /// \return A unique subscription token used to unsubscribe.
            size_t Add(const Action<const void*, const TEventArgs&>& fnHandler) {
                /// Assign monotonic unique subscription token.
                size_t nAssignedToken = m_nNextToken++;

                /// Append subscriber to registration list.
                m_lstSubscribers.Add(SubscriberEntry(nAssignedToken, fnHandler));
                return nAssignedToken;
            }

            /// \brief Subscribes a generic callable object (lambda or function pointer).
            template <typename F, typename = std::enable_if_t<!std::is_same_v<std::decay_t<F>, EventHandler> && !std::is_same_v<std::decay_t<F>, Action<const void*, const TEventArgs&>> && std::is_invocable_v<std::decay_t<F>, const void*, const TEventArgs&>>>
            size_t Add(F&& fnHandler) {
                return Add(Action<const void*, const TEventArgs&>(std::forward<F>(fnHandler)));
            }

            /// \brief Subscribes a member method on an instance object.
            template <typename TClass>
            size_t Add(TClass* pInstance, void (TClass::*pMethod)(const void*, const TEventArgs&)) {
                return Add([pInstance, pMethod](const void* pSender, const TEventArgs& e) {
                    if (pInstance != nullptr && pMethod != nullptr) {
                        (pInstance->*pMethod)(pSender, e);
                    }
                });
            }

            /// \brief Multicast addition operator. Subscribes an Action callback.
            size_t operator+=(const Action<const void*, const TEventArgs&>& fnHandler) {
                return Add(fnHandler);
            }

            /// \brief Multicast addition operator. Subscribes a generic callable object.
            template <typename F, typename = std::enable_if_t<!std::is_same_v<std::decay_t<F>, EventHandler> && !std::is_same_v<std::decay_t<F>, Action<const void*, const TEventArgs&>> && std::is_invocable_v<std::decay_t<F>, const void*, const TEventArgs&>>>
            size_t operator+=(F&& fnHandler) {
                return Add(std::forward<F>(fnHandler));
            }

            /// \brief Multicast addition operator. Appends all subscribers from another EventHandler.
            EventHandler& operator+=(const EventHandler& other) {
                int iCount = other.m_lstSubscribers.GetCount();
                for (int i = 0; i < iCount; ++i) {
                    Add(other.m_lstSubscribers[i].m_fnAction);
                }
                return *this;
            }

            /// \brief Unsubscribes a subscriber matching the specified subscription token.
            /// \param nToken The subscription token returned from Add.
            /// \return true if a subscriber was found and removed; otherwise, false.
            bool Remove(size_t nToken) {
                /// Linearly search registry for matching subscription token.
                for (int i = 0; i < m_lstSubscribers.GetCount(); ++i) {
                    if (m_lstSubscribers[i].m_nToken == nToken) {
                        m_lstSubscribers.RemoveAt(i);
                        return true;
                    }
                }
                return false;
            }

            /// \brief Multicast subtraction operator. Unsubscribes using a subscription token.
            bool operator-=(size_t nToken) {
                return Remove(nToken);
            }

            /// \brief Removes all registered subscribers.
            void Clear() {
                m_lstSubscribers.Clear();
            }

            /// \brief Sequentially invokes all registered subscriber callbacks in FIFO order.
            /// \param pSender Pointer to the source object initiating the event.
            /// \param e The event data payload.
            void Invoke(const void* pSender, const TEventArgs& e) const {
                /// Sequential multicast dispatch to all registered callbacks.
                int iCount = m_lstSubscribers.GetCount();
                for (int i = 0; i < iCount; ++i) {
                    m_lstSubscribers[i].m_fnAction.Invoke(pSender, e);
                }
            }

            /// \brief Invocation call operator.
            void operator()(const void* pSender, const TEventArgs& e) const {
                Invoke(pSender, e);
            }

            /// \brief Checks whether the multicast event handler has zero registered subscribers.
            bool IsEmpty() const {
                return m_lstSubscribers.GetCount() == 0;
            }

            /// \brief Gets the number of currently active subscribers.
            size_t GetSubscriberCount() const {
                return static_cast<size_t>(m_lstSubscribers.GetCount());
            }

            /// \brief Boolean conversion operator. Returns true if there are registered subscribers.
            explicit operator bool() const {
                return !IsEmpty();
            }
        };

        template <typename TEventArgs = EventArgs>
        EventHandler() -> EventHandler<TEventArgs>;

    }
}
